<div class="col-lg-8">
    <div class="jumbotron">
        <form method="post" class="form-inline" action="<?php echo $this->url('application', ['action' => 'login']); ?>">
            <input class="form-control" name="email" id="email" placeholder="Login">
            <input class="form-control" name="password" id="password" type="password" placeholder="Password">
            <button class="btn-primary" type="submit">Войти</button>
        </form>
    </div>
</div>
